/** @type {import('tailwindcss').Config} */
// Aligned with the Nori design tokens (projects/core/src/lib/styles/_tokens.scss)
module.exports = {
  content: [
    './src/**/*.{html,ts}',
    './projects/**/*.{html,ts}',
  ],
  theme: {
    extend: {
      colors: {
        teal: {
          50: 'var(--teal-50)',
          100: 'var(--teal-100)',
          200: 'var(--teal-200)',
          300: 'var(--teal-300)',
          400: 'var(--teal-400)',
          500: 'var(--teal-500)',
          600: 'var(--teal-600)',
          700: 'var(--teal-700)',
          800: 'var(--teal-800)',
          900: 'var(--teal-900)',
        },
        navy: {
          50: 'var(--navy-50)',
          100: 'var(--navy-100)',
          200: 'var(--navy-200)',
          300: 'var(--navy-300)',
          400: 'var(--navy-400)',
          500: 'var(--navy-500)',
          600: 'var(--navy-600)',
          700: 'var(--navy-700)',
          800: 'var(--navy-800)',
          900: 'var(--navy-900)',
        },
        ok: { DEFAULT: 'var(--ok)', light: 'var(--ok-l)', dark: 'var(--ok-d)' },
        hi: { DEFAULT: 'var(--hi)', light: 'var(--hi-l)', dark: 'var(--hi-d)' },
        lo: { DEFAULT: 'var(--lo)', light: 'var(--lo-l)', dark: 'var(--lo-d)' },
        info: { DEFAULT: 'var(--info)', light: 'var(--info-l)', dark: 'var(--info-d)' },
        surface: {
          bg: 'var(--bg)',
          card: 'var(--card)',
          sunken: 'var(--sunken)',
          elevated: 'var(--elevated)',
        },
        border: {
          s: 'var(--border-s)',
          m: 'var(--border-m)',
          h: 'var(--border-h)',
        },
        type: {
          1: 'var(--t1)',
          2: 'var(--t2)',
          3: 'var(--t3)',
          4: 'var(--t4)',
          inv: 'var(--ti)',
        },
      },
      fontFamily: {
        sans: ['var(--font-sans)', 'sans-serif'],
        heading: ['var(--font-heading)', 'sans-serif'],
        mono: ['var(--font-mono)', 'monospace'],
      },
      spacing: {
        '1': '0.25rem',
        '2': '0.5rem',
        '3': '0.75rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '8': '2rem',
        '10': '2.5rem',
        '12': '3rem',
        '16': '4rem',
        '20': '5rem',
        'touch': '44px',
      },
      fontSize: {
        'caption': '0.6875rem',
        'xs': '0.75rem',
        'sm': '0.875rem',
        'base': '1rem',
        'lg': '1.125rem',
        'xl': '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
      },
      borderRadius: {
        'sm': '0.25rem',
        'md': '0.5rem',
        'lg': '0.75rem',
        'xl': '1rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        'full': '9999px',
      },
      boxShadow: {
        'e0': 'var(--e0)',
        'e1': 'var(--e1)',
        'e2': 'var(--e2)',
        'e3': 'var(--e3)',
        'e4': 'var(--e4)',
        'e5': 'var(--e5)',
        'et': 'var(--et)',
        'et2': 'var(--et2)',
      },
      transitionDuration: {
        'fast': '120ms',
        'base': '200ms',
        'slow': '360ms',
        'xslow': '500ms',
      },
      transitionTimingFunction: {
        'eout': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'eio': 'cubic-bezier(0.45, 0, 0.55, 1)',
        'spring': 'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
      },
    },
  },
  plugins: [],
};
